### ISSUE TITLE
Colorize prompt

### ISSUE THREAD

**Issue by antonmedv** [aantthony/node-color-readline#2]
Hi,

Got strange offset with clalk + prompt:
```
>    |       test
```

```js
rl.question(chalk.cyan('> '), fn)
```

**Comment by aantthony** [comment]
The library only supports color on the user input, not the prompt prefix. The problem is that Node thinks the prompt string is longer than it is due to the control characters.

It would be a nice feature to have if anybody needs it, but I have no plans to build it myself.
